# ios/Podfile
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
     '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
 end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')  # ✅ load helper

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'm4uapp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Chỉ liệt kê quyền bạn thực sự dùng trong JS
  setup_permissions([
    'Camera',
    'PhotoLibrary',
  ])

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end

# target 'OneSignalNotificationServiceExtension' do
#   pod 'OneSignalXCFramework', '>= 5.0.0', '< 6.0'
# end
