export const POST_LOGIN_PHONE_NUMBER = "POST_LOGIN_PHONE_NUMBER";
export const POST_LOGIN_PHONE_NUMBER_SUCCESS = "POST_LOGIN_PHONE_NUMBER_SUCCESS";
export const POST_LOGIN_PHONE_NUMBER_FAILURE = "POST_LOGIN_PHONE_NUMBER_FAILURE";
export const CHANGE_STATUS_POST_LOGIN_PHONE_NUMBER = "CHANGE_STATUS_POST_LOGIN_PHONE_NUMBER";
//save login
export const SAVE_LOGIN = "SAVE_LOGIN"
export const DONT_SAVE_LOGIN = "DONT_SAVE_LOGIN"
// log out
export const LOG_OUT = "LOG_OUT"
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS"
export const LOG_OUT_FAILURE = "LOG_OUT_FAILURE"
export const CHANGE_LOG_OUT = "CHANGE_LOG_OUT"
// TOKEN_EXPIRED
export const POST_LOGOUT_TOKEN_EXPIRED = "POST_LOGOUT_TOKEN_EXPIRED"

