export const GET_LATEST_HEARTRATE_REQUEST = "GET_LATEST_HEARTRATE_REQUEST";
export const GET_LATEST_HEARTRATE_SUCCESS = "GET_LATEST_HEARTRATE_SUCCESS";
export const GET_LATEST_HEARTRATE_FAILURE = "GET_LATEST_HEARTRATE_FAILURE";

export const GET_HISTORICAL_HEARTRATE_REQUEST = "GET_HISTORICAL_HEARTRATE_REQUEST";
export const GET_HISTORICAL_HEARTRATE_SUCCESS = "GET_HISTORICAL_HEARTRATE_SUCCESS";
export const GET_HISTORICAL_HEARTRATE_FAILURE = "GET_HISTORICAL_HEARTRATE_FAILURE";

export const HEARTRATE_ANALYZE_REQUEST = "HEARTRATE_ANALYZE_REQUEST";
export const HEARTRATE_ANALYZE_SUCCESS = "HEARTRATE_ANALYZE_SUCCESS";
export const HEARTRATE_ANALYZE_FAILURE = "HEARTRATE_ANALYZE_FAILURE";

export const GET_HEARTRATE_TREND_REQUEST = "GET_HEARTRATE_TREND_REQUEST";
export const GET_HEARTRATE_TREND_SUCCESS = "GET_HEARTRATE_TREND_SUCCESS";
export const GET_HEARTRATE_TREND_FAILURE = "GET_HEARTRATE_TREND_FAILURE";
