export const GET_LATEST_HEARTRATE_REQUEST = "GET_LATEST_HEARTRATE_REQUEST";
export const GET_LATEST_HEARTRATE_SUCCESS = "GET_LATEST_HEARTRATE_SUCCESS";
export const GET_LATEST_HEARTRATE_FAILURE = "GET_LATEST_HEARTRATE_FAILURE";
