export const SHOW_LOADING = "SHOW_LOADING";
export const SHOW_LOADING_DEEP_LINK = "SHOW_LOADING_DEEP_LINK";
export const SHOW_LOADING_FULL_SCREEN = "SHOW_LOADING_FULL_SCREEN";

export const SHOW_ALERT_GLOBAL = "SHOW_ALERT_GLOBAL";

export const SHOW_POP_UP_SUCCESS = "SHOW_POP_UP_SUCCESS";
export const SHOW_POP_UP_FAILURE = "SHOW_POP_UP_FAILURE";

export const SET_DISABLED_BUTTON = "SET_DISABLED_BUTTON";
