export const GET_SETTING = "GET_SETTING";
export const GET_SETTING_SUCCESS = "GET_SETTING_SUCCESS";
export const GET_SETTING_FAILURE = "GET_SETTING_FAILURE";
export const CHANGE_STATUS_GET_SETTING = "CHANGE_STATUS_GET_SETTING";